remote_theme: just-the-docs/just-the-docs

title: Yamux
description: A .NET implementation of the HashiCorp Yamux multiplexing protocol
color_scheme: dark

aux_links:
  "Yamux on GitHub":
    - "https://github.com/pableess/yamux-dotnet"
  "NuGet":
    - "https://www.nuget.org/packages/Yamux"

footer_content: "Copyright &copy; Paul Bleess. Distributed under the MIT license."

callouts:
  tip:
    color: green
  warn:
    color: yellow
  note:
    color: blue
  danger:
    color: red