name: Build and Publish NuGet Package
on:
  push:
    branches:
      - main
      - release/**
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    permissions:
      contents: write  # Ensure write permission in job context
      id-token: write  # enable GitHub OIDC token issuance for this job
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
       # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user:  ${{ secrets.NUGET_USER }} 
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'      
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
      - name: Pack
        run: dotnet pack src/Yamux.csproj --no-build --configuration Release --output ./nupkg
      - name: Set Version Variable
        run: |
          VERSION=$(grep '<VersionPrefix>' Directory.Build.props | sed -E 's/.*>(.*)<.*/\1/')-$(grep '<VersionSuffix>' Directory.Build.props | sed -E 's/.*>(.*)<.*/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Publish to NuGet
        if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/tags/v'))
        run: dotnet nuget push ./nupkg/*.nupkg ./nupkg/*.snupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
      - name: Create Git Tag
        if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/tags/v'))
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v$VERSION
          git push origin v$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

