name: Build and Publish NuGet Package
on:
  push:
    branches:
      - main
      - release/**
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
      - name: Pack
        run: dotnet pack src/Yamux/Yamux.csproj --no-build --configuration Release --output ./nupkg
      - name: Set Version Variable
        run: |
          VERSION=$(grep '<VersionPrefix>' Directory.Build.props | sed -E 's/.*>(.*)<.*/\1/')-$(grep '<VersionSuffix>' Directory.Build.props | sed -E 's/.*>(.*)<.*/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Git Tag
        if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release') ||  startsWith(github.ref, 'refs/tags/v'))
        run: |
          git tag v$VERSION
          git push origin v$VERSION
      - name: Publish to NuGet
        if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release') ||  startsWith(github.ref, 'refs/tags/v'))
        run: dotnet nuget push ./nupkg/*.nupkg ./nupkg/*.snupkg --api-key ${{ secrets.NUGET_API_KEY }}
    
