name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
      - name: Pack
        run: dotnet pack src/Yamux/Yamux.csproj --no-build --configuration Release --output ./nupkg
      - name: Publish to NuGet
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet nuget push ./nupkg/*.nupkg ./nupkg/*.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --
